export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_RESET = "ADD_ITEM_RESET";
export const ADD_ITEM_FAIL = "ADD_ITEM_FAIL";

export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAIL = "GET_ITEM_FAIL";

export const REMOVE_ITEM_REQUEST = "REMOVE_ITEM_REQUEST";
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS";
export const REMOVE_ITEM_RESET = "REMOVE_ITEM_RESET";
export const REMOVE_ITEM_FAIL = "REMOVE_ITEM_FAIL";

export const CLEAR_CART_ITEM = "CLEAR_CART_ITEM";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
